# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv

    - name: Check Python version
      run: |
        which python
        python --version
        which python3
        python3 --version
        which python3.9
        python3.9 --version
        which pipenv
        pipenv --version

    - name: Run pipenv install
      run: |
        pipenv install --deploy
        
    - name: Build
      run: |
        pipenv run fsbuild/build

    - name: Bundle
      run: |
        pipenv run fsbuild/bundle




 


