name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Linux_x86-64:
  #   runs-on: ubuntu-18.04

  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0

  #   - name: Set up Python 3.9
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: 3.9

  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip pipenv

  #   - name: Check Python version
  #     run: |
  #       which python
  #       python --version
  #       which python3
  #       python3 --version
  #       which python3.9
  #       python3.9 --version
  #       which pipenv
  #       pipenv --version

  #   - name: Update version
  #     run: fsbuild/version --update --auto

  #   - name: Run pipenv install
  #     run: |
  #       pipenv install --deploy
        
  #   - name: Build
  #     run: |
  #       pipenv run fsbuild/build

  #   - name: Bundle
  #     run: |
  #       pipenv run fsbuild/bundle

  #   - name: Archive
  #     run: fsbuild/archive

  #   - uses: actions/upload-artifact@v2
  #     with:
  #       name: Linux_x86-64
  #       path: fsbuild/_dist/*

  #   - name: Install dropbox package
  #     run: python3 -m pip install dropbox

  #   - name: Upload build to Dropbox folder
  #     run: fsbuild/upload
  #     env:
  #       DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
  #       DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}

  Windows_x86-64:
    runs-on: windows-2016

    # defaults:
    #   run:
    #     shell: msys2 {0}
       
    steps:

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Check Python version
      run: |
       python3 -c "import sys; print(sys.path)"

    - uses: msys2/setup-msys2@v2

    - name: Check Python version
      shell: msys2 {0}
      run: |
        which python
        python --version
        which python3
        python3 --version
        which python3.9
        python3.9 --version
        which pipenv
        pipenv --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip pipenv

    - name: Check pipenv version
      shell: msys2 {0}
      run: |
        which pipenv
        pipenv --version

    - name: Update version
      shell: msys2 {0}
      run: fsbuild/version --update --auto

    - name: Run pipenv install
      shell: msys2 {0}
      run: |
        pipenv install --deploy

        
    - name: Build
      run: |
        pipenv run fsbuild/build

    - name: Bundle
      run: |
        pipenv run fsbuild/bundle

    - name: Archive
      run: fsbuild/archive

    - uses: actions/upload-artifact@v2
      with:
        name: Linux_x86-64
        path: fsbuild/_dist/*

    - name: Install dropbox package
      run: python3 -m pip install dropbox

    - name: Upload build to Dropbox folder
      run: fsbuild/upload
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
